PostgreSQL:
  restart: always
  image: postgres:10
  ports:
    - "5432:5432"
  environment:
    - DEBUG=true
    - POSTGRES_PASSWORD=test
    - POSTGRES_USER=test
    - POSTGRES_DB=shkaff
  volumes:
    - ./shkaff.sql:/docker-entrypoint-initdb.d/shkaff.sql

MongoDB:
  restart: always
  image: mongo:latest
  environment:
    - MONGODB_USER=test
    - MONGODB_DATABASE=test
    - MONGODB_PASS=test
  ports:
    - "27017:27017"
  volumes:
    - /srv/docker/mongodb:/var/lib/mongodb
  command:
    - --storageEngine=wiredTiger